name: CI Build

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - run: npm install
      - run: npm run build
